version: "3"
services:
  # exercise3:
  #   build: .
  #   ports:
  #     - "9003:9003"
  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
  mongodbbackup:
    image: mongo
    volumes:
      - ./dataBackup/db:/dataBackup/db
    ports:
      - 27018:27017
    command:
      - '--logpath'
      - '/var/log/mongodb/mongodBackup.log'
  redis:
    image: redis
    ports:
      - 6379:6379
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
